[package]
name = "call_py_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyembed = "0.24.0"
pyo3 = "0.17.3"


